id: P557656CD
initial_creation_type: ocr
source_metadata:
  volumes:
    d82c896b6fb148709ab33a094e64ac9a:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: སྤེལ་མར་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
